package com.cms.pp.cms.pp.enums;

import lombok.Getter;

@Getter
public enum PrivilegeName {
    ADMIN_PANEL("ADMIN_PANEL"),
    REMOVE_TAGS("REMOVE_TAGS"),
    ADD_TAGS_CMS("ADD_TAGS_CMS"),
    ADD_LANGUAGE("ADD_LANGUAGE"),
    REMOVE_LANGUAGE("REMOVE_LANGUAGE"),
    EDIT_LANGUAGE("EDIT_LANGUAGE"),
    EDIT_USER("EDIT_USER"),
    EDIT_CMS_USER("EDIT_CMS_USER"),
    REMOVE_USER("REMOVE_USER"),
    ADD_TRANSLATION("ADD_TRANSLATION"),
    REMOVE_TRANSLATION("REMOVE_TRANSLATION"),
    EDIT_TRANSLATION("EDIT_TRANSLATION"),
    READ_CMS_USERS("READ_CMS_USERS"),
    READ_PRIVILEGE("READ_PRIVILEGE"),
    WRITE_COMMENT("WRITE_COMMENT"),
    REMOVE_COMMENT("REMOVE_COMMENT"),
    EDIT_COMMENT("EDIT_COMMENT"),
    EDIT_OWN_COMMENT("EDIT_OWN_COMMENT"),
    EDIT_ARTICLE("EDIT_ARTICLE"),
    EDIT_ADMINS_ARTICLE("EDIT_ADMINS_ARTICLE"),
    EDIT_MODERATORS_ARTICLE("EDIT_MODERATORS_ARTICLE"),
    EDIT_EDITORS_ARTICLE("EDIT_EDITORS_ARTICLE"),
    ADD_ROLE("ADD_ROLE"),
    EDIT_ROLE("EDIT_ROLE"),
    EDIT_USER_ROLE("EDIT_USER_ROLE"),
    ADD_CMS_USER("ADD_CMS_USER"),
    ADD_ARTICLE("ADD_ARTICLE"),
    REMOVE_ARTICLE("REMOVE_ARTICLE"),
    EDIT_TAG("EDIT_TAG"),
    MANAGE_CONFIG_FLAGS("MANAGE_CONFIG_FLAGS"),
    REMOVE_ROLE("REMOVE_ROLE"),
    PUBLISH_ARTICLE("PUBLISH_ARTICLE"),
    ADMIN_USERS_PRIVILEGE_ACCESS("ADMIN_USERS_PRIVILEGE_ACCESS")
    ;
    public final String privilegeName;
    
    private PrivilegeName(String privilegeName) { this.privilegeName = privilegeName; }

}
